# Generated by Django 5.2.17 on 2026-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
