# Generated by Django 5.2.17 on 2026-08-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
        ("users", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="packages.agency",
            ),
        ),
    ]
