# Generated by Django 5.2.17 on 2026-08-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
