# Generated by Django 5.2.17 on 2026-09-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packagefavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="packages.package"
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="packagereview",
            name="package_purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="packages.packagepurchase",
            ),
        ),
    ]
