# Generated by Django 5.2.17 on 2026-08-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_flight_id', models.PositiveIntegerField()),
                ('return_flight_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.agency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.hotel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
