# Generated by Django 5.2.17 on 2026-09-11 02:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="city_name_lower_unique",
            ),
        ),
    ]
